### ISSUE TITLE
license for labs?

### ISSUE THREAD

**Issue by grady** [moderndive/moderndive_labs#20]
Hi,
Thanks for making these labs available. I am curious what license is this code distributed under?

The book itself is a Creative Commons license, but there doesn't seem to be anything stated about the license status of the labs.

I would like to fork some of this code and create problem set repositories for use with Github Classroom. I want to make sure that the authors are OK with this.

**Comment by rudeboybert** [comment]
Hey @grady thanks for reaching out and for the considerate question. I just added a CC license, so fork away!
